#include "src/game/envfx_snow.h"

const GeoLayout omega_2_LoD_Switch_opt0_Cap_State_Switch_opt1_Capless_Switch_opt1[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_SWITCH_CASE(0, geo_switch_mario_eyes),
		GEO_OPEN_NODE(),
			GEO_NODE_START(),
			GEO_OPEN_NODE(),
				GEO_DISPLAY_LIST(LAYER_TRANSPARENT, omega_Head_DL_mesh_layer_1_mat_override_OmegaMouth_1),
				GEO_DISPLAY_LIST(LAYER_TRANSPARENT, omega_Head_DL_mesh_layer_4_mat_override_OmegaMouth_1),
				GEO_DISPLAY_LIST(LAYER_TRANSPARENT, omega_Head_DL_mesh_layer_5_mat_override_OmegaMouth_1),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout omega_2_LoD_Switch_opt0_Cap_State_Switch_opt1_Capless_Switch_opt0_Eye_State_Switch_opt1[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, omega_Head_DL_mesh_layer_1_mat_override_OmegaMouth_1),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, omega_Head_DL_mesh_layer_4_mat_override_OmegaMouth_1),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, omega_Head_DL_mesh_layer_5_mat_override_OmegaMouth_1),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout omega_2_LoD_Switch_opt0_Cap_State_Switch_opt1_Capless_Switch_opt0_Eye_State_Switch_opt2[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, omega_Head_DL_mesh_layer_1_mat_override_OmegaMouth_1),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, omega_Head_DL_mesh_layer_4_mat_override_OmegaMouth_1),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, omega_Head_DL_mesh_layer_5_mat_override_OmegaMouth_1),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout omega_2_LoD_Switch_opt0_Cap_State_Switch_opt1_Capless_Switch_opt0_Eye_State_Switch_opt3[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, omega_Head_DL_mesh_layer_1_mat_override_OmegaMouth_1),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, omega_Head_DL_mesh_layer_4_mat_override_OmegaMouth_1),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, omega_Head_DL_mesh_layer_5_mat_override_OmegaMouth_1),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout omega_2_LoD_Switch_opt0_Cap_State_Switch_opt1_Capless_Switch_opt0_Eye_State_Switch_opt4[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, omega_Head_DL_mesh_layer_1_mat_override_OmegaMouth_1),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, omega_Head_DL_mesh_layer_4_mat_override_OmegaMouth_1),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, omega_Head_DL_mesh_layer_5_mat_override_OmegaMouth_1),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout omega_2_LoD_Switch_opt0_Cap_State_Switch_opt1_Capless_Switch_opt0_Eye_State_Switch_opt5[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, omega_Head_DL_mesh_layer_1_mat_override_OmegaMouth_1),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, omega_Head_DL_mesh_layer_4_mat_override_OmegaMouth_1),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, omega_Head_DL_mesh_layer_5_mat_override_OmegaMouth_1),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout omega_2_LoD_Switch_opt0_Cap_State_Switch_opt1_Capless_Switch_opt0_Eye_State_Switch_opt6[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, omega_Head_DL_mesh_layer_1_mat_override_OmegaMouth_1),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, omega_Head_DL_mesh_layer_4_mat_override_OmegaMouth_1),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, omega_Head_DL_mesh_layer_5_mat_override_OmegaMouth_1),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout omega_2_LoD_Switch_opt0_Cap_State_Switch_opt1_Capless_Switch_opt0_Eye_State_Switch_opt7[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, omega_Head_DL_mesh_layer_1_mat_override_OmegaMouth_1),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, omega_Head_DL_mesh_layer_4_mat_override_OmegaMouth_1),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, omega_Head_DL_mesh_layer_5_mat_override_OmegaMouth_1),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout omega_2_LoD_Switch_opt0_Cap_State_Switch_opt1_Left_Hand_Switch_opt1[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(LAYER_OPAQUE, 139, 0, 0, NULL),
		GEO_OPEN_NODE(),
			GEO_ASM(1, geo_mario_hand_foot_scaler),
			GEO_SCALE(LAYER_FORCE, 65536),
			GEO_OPEN_NODE(),
				GEO_DISPLAY_LIST(LAYER_TRANSPARENT, omega_Left_Hand_DL_mesh_layer_1_mat_override_OmegaMouth_1),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout omega_2_LoD_Switch_opt0_Cap_State_Switch_opt1_Right_Hand_Switch_opt1[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(LAYER_OPAQUE, 139, 1, 0, NULL),
		GEO_OPEN_NODE(),
			GEO_ASM(0, geo_mario_hand_foot_scaler),
			GEO_SCALE(LAYER_FORCE, 65536),
			GEO_OPEN_NODE(),
				GEO_DISPLAY_LIST(LAYER_TRANSPARENT, omega_Right_Hand_DL_mesh_layer_1_mat_override_OmegaMouth_1),
			GEO_CLOSE_NODE(),
			GEO_HELD_OBJECT(0, 0, 0, 0, geo_switch_mario_hand_grab_pos),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout omega_2_LoD_Switch_opt0_Cap_State_Switch_opt1_Right_Hand_Switch_opt2[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(LAYER_OPAQUE, 139, 1, 0, NULL),
		GEO_OPEN_NODE(),
			GEO_ASM(0, geo_mario_hand_foot_scaler),
			GEO_SCALE(LAYER_FORCE, 65536),
			GEO_OPEN_NODE(),
				GEO_DISPLAY_LIST(LAYER_TRANSPARENT, omega_Right_Hand_DL_mesh_layer_1_mat_override_OmegaMouth_1),
			GEO_CLOSE_NODE(),
			GEO_HELD_OBJECT(0, 0, 0, 0, geo_switch_mario_hand_grab_pos),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout omega_2_LoD_Switch_opt0_Cap_State_Switch_opt1_Right_Hand_Switch_opt3[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(LAYER_OPAQUE, 139, 1, 0, NULL),
		GEO_OPEN_NODE(),
			GEO_ASM(0, geo_mario_hand_foot_scaler),
			GEO_SCALE(LAYER_FORCE, 65536),
			GEO_OPEN_NODE(),
				GEO_DISPLAY_LIST(LAYER_TRANSPARENT, omega_Right_Hand_DL_mesh_layer_1_mat_override_OmegaMouth_1),
			GEO_CLOSE_NODE(),
			GEO_HELD_OBJECT(0, 0, 0, 0, geo_switch_mario_hand_grab_pos),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout omega_2_LoD_Switch_opt0_Cap_State_Switch_opt1_Right_Hand_Switch_opt4[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(LAYER_OPAQUE, 139, 1, 0, NULL),
		GEO_OPEN_NODE(),
			GEO_ASM(0, geo_mario_hand_foot_scaler),
			GEO_SCALE(LAYER_FORCE, 65536),
			GEO_OPEN_NODE(),
				GEO_DISPLAY_LIST(LAYER_TRANSPARENT, omega_Right_Hand_DL_mesh_layer_1_mat_override_OmegaMouth_1),
			GEO_CLOSE_NODE(),
			GEO_HELD_OBJECT(0, 0, 0, 0, geo_switch_mario_hand_grab_pos),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout omega_2_LoD_Switch_opt0_Cap_State_Switch_opt1[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 163, 0, NULL),
		GEO_OPEN_NODE(),
			GEO_ANIMATED_PART(LAYER_TRANSPARENT, 0, 0, 0, omega_Butt_mesh_layer_1),
			GEO_OPEN_NODE(),
				GEO_ASM(0, geo_move_mario_part_from_parent),
				GEO_ASM(0, geo_mario_tilt_torso),
				GEO_ROTATION_NODE(LAYER_FORCE, 0, 0, 0),
				GEO_OPEN_NODE(),
					GEO_ANIMATED_PART(LAYER_TRANSPARENT, 67, 0, 0, omega_Torso_mesh_layer_1),
					GEO_OPEN_NODE(),
						GEO_ANIMATED_PART(LAYER_OPAQUE, 138, 0, 0, NULL),
						GEO_OPEN_NODE(),
							GEO_ASM(0, geo_mario_head_rotation),
							GEO_ROTATION_NODE(LAYER_FORCE, 0, 0, 0),
							GEO_OPEN_NODE(),
								GEO_SWITCH_CASE(0, geo_switch_mario_cap_on_off),
								GEO_OPEN_NODE(),
									GEO_NODE_START(),
									GEO_OPEN_NODE(),
										GEO_SWITCH_CASE(0, geo_switch_mario_eyes),
										GEO_OPEN_NODE(),
											GEO_NODE_START(),
											GEO_OPEN_NODE(),
												GEO_DISPLAY_LIST(LAYER_TRANSPARENT, omega_Head_DL_mesh_layer_1),
												GEO_DISPLAY_LIST(LAYER_TRANSPARENT, omega_Head_DL_mesh_layer_4),
												GEO_DISPLAY_LIST(LAYER_TRANSPARENT, omega_Head_DL_mesh_layer_5),
											GEO_CLOSE_NODE(),
											GEO_BRANCH(1, omega_2_LoD_Switch_opt0_Cap_State_Switch_opt1_Capless_Switch_opt0_Eye_State_Switch_opt1),
											GEO_BRANCH(1, omega_2_LoD_Switch_opt0_Cap_State_Switch_opt1_Capless_Switch_opt0_Eye_State_Switch_opt2),
											GEO_BRANCH(1, omega_2_LoD_Switch_opt0_Cap_State_Switch_opt1_Capless_Switch_opt0_Eye_State_Switch_opt3),
											GEO_BRANCH(1, omega_2_LoD_Switch_opt0_Cap_State_Switch_opt1_Capless_Switch_opt0_Eye_State_Switch_opt4),
											GEO_BRANCH(1, omega_2_LoD_Switch_opt0_Cap_State_Switch_opt1_Capless_Switch_opt0_Eye_State_Switch_opt5),
											GEO_BRANCH(1, omega_2_LoD_Switch_opt0_Cap_State_Switch_opt1_Capless_Switch_opt0_Eye_State_Switch_opt6),
											GEO_BRANCH(1, omega_2_LoD_Switch_opt0_Cap_State_Switch_opt1_Capless_Switch_opt0_Eye_State_Switch_opt7),
										GEO_CLOSE_NODE(),
									GEO_CLOSE_NODE(),
									GEO_BRANCH(1, omega_2_LoD_Switch_opt0_Cap_State_Switch_opt1_Capless_Switch_opt1),
								GEO_CLOSE_NODE(),
								GEO_TRANSLATE_ROTATE(LAYER_FORCE, 115, -51, 126, -15, 33, -133),
								GEO_OPEN_NODE(),
									GEO_ASM(1, geo_mario_rotate_wing_cap_wings),
									GEO_ROTATION_NODE(LAYER_FORCE, 0, 0, 0),
									GEO_OPEN_NODE(),
									GEO_CLOSE_NODE(),
								GEO_CLOSE_NODE(),
								GEO_TRANSLATE_ROTATE(LAYER_FORCE, 115, -51, -126, 15, -33, -133),
								GEO_OPEN_NODE(),
									GEO_ASM(0, geo_mario_rotate_wing_cap_wings),
									GEO_ROTATION_NODE(LAYER_FORCE, 0, 0, 0),
									GEO_OPEN_NODE(),
									GEO_CLOSE_NODE(),
								GEO_CLOSE_NODE(),
							GEO_CLOSE_NODE(),
						GEO_CLOSE_NODE(),
						GEO_ANIMATED_PART(LAYER_OPAQUE, 91, -10, 79, NULL),
						GEO_OPEN_NODE(),
							GEO_ANIMATED_PART(LAYER_TRANSPARENT, 0, 0, 0, omega_Left_Arm_Color_mesh_layer_1),
							GEO_OPEN_NODE(),
								GEO_ANIMATED_PART(LAYER_TRANSPARENT, 129, 20, 0, omega_Left_Forearm_mesh_layer_1),
								GEO_OPEN_NODE(),
									GEO_SWITCH_CASE(1, geo_switch_mario_hand),
									GEO_OPEN_NODE(),
										GEO_NODE_START(),
										GEO_OPEN_NODE(),
											GEO_ANIMATED_PART(LAYER_OPAQUE, 139, 0, 0, NULL),
											GEO_OPEN_NODE(),
												GEO_ASM(1, geo_mario_hand_foot_scaler),
												GEO_SCALE(LAYER_FORCE, 65536),
												GEO_OPEN_NODE(),
													GEO_DISPLAY_LIST(LAYER_TRANSPARENT, omega_Left_Hand_DL_mesh_layer_1),
												GEO_CLOSE_NODE(),
											GEO_CLOSE_NODE(),
										GEO_CLOSE_NODE(),
										GEO_BRANCH(1, omega_2_LoD_Switch_opt0_Cap_State_Switch_opt1_Left_Hand_Switch_opt1),
									GEO_CLOSE_NODE(),
								GEO_CLOSE_NODE(),
							GEO_CLOSE_NODE(),
						GEO_CLOSE_NODE(),
						GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 92, -10, -79, 2, 0, 0),
						GEO_OPEN_NODE(),
							GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, NULL),
							GEO_OPEN_NODE(),
								GEO_ANIMATED_PART(LAYER_TRANSPARENT, 0, 0, 0, omega_Right_Arm_Color_mesh_layer_1),
								GEO_OPEN_NODE(),
									GEO_ANIMATED_PART(LAYER_TRANSPARENT, 129, 21, 0, omega_Right_Forearm_mesh_layer_1),
									GEO_OPEN_NODE(),
										GEO_SWITCH_CASE(0, geo_switch_mario_hand),
										GEO_OPEN_NODE(),
											GEO_NODE_START(),
											GEO_OPEN_NODE(),
												GEO_ANIMATED_PART(LAYER_OPAQUE, 139, 1, 0, NULL),
												GEO_OPEN_NODE(),
													GEO_ASM(0, geo_mario_hand_foot_scaler),
													GEO_SCALE(LAYER_FORCE, 65536),
													GEO_OPEN_NODE(),
														GEO_DISPLAY_LIST(LAYER_TRANSPARENT, omega_Right_Hand_DL_mesh_layer_1),
													GEO_CLOSE_NODE(),
													GEO_HELD_OBJECT(0, 0, 0, 0, geo_switch_mario_hand_grab_pos),
												GEO_CLOSE_NODE(),
											GEO_CLOSE_NODE(),
											GEO_BRANCH(1, omega_2_LoD_Switch_opt0_Cap_State_Switch_opt1_Right_Hand_Switch_opt1),
											GEO_BRANCH(1, omega_2_LoD_Switch_opt0_Cap_State_Switch_opt1_Right_Hand_Switch_opt2),
											GEO_BRANCH(1, omega_2_LoD_Switch_opt0_Cap_State_Switch_opt1_Right_Hand_Switch_opt3),
											GEO_BRANCH(1, omega_2_LoD_Switch_opt0_Cap_State_Switch_opt1_Right_Hand_Switch_opt4),
										GEO_CLOSE_NODE(),
									GEO_CLOSE_NODE(),
								GEO_CLOSE_NODE(),
							GEO_CLOSE_NODE(),
						GEO_CLOSE_NODE(),
					GEO_CLOSE_NODE(),
				GEO_CLOSE_NODE(),
				GEO_ANIMATED_PART(LAYER_OPAQUE, -3, -8, 42, NULL),
				GEO_OPEN_NODE(),
					GEO_ANIMATED_PART(LAYER_TRANSPARENT, 0, 0, 0, omega_Left_Thigh_Color_mesh_layer_1),
					GEO_OPEN_NODE(),
						GEO_DISPLAY_LIST(LAYER_TRANSPARENT, omega_Left_Thigh_Color_mesh_layer_4),
						GEO_ANIMATED_PART(LAYER_TRANSPARENT, 148, 0, 0, omega_Left_Leg_mesh_layer_4),
						GEO_OPEN_NODE(),
							GEO_ANIMATED_PART(LAYER_TRANSPARENT, 154, 0, 0, omega_Left_Shoe_mesh_layer_1),
							GEO_OPEN_NODE(),
								GEO_DISPLAY_LIST(LAYER_TRANSPARENT, omega_Left_Shoe_mesh_layer_5),
							GEO_CLOSE_NODE(),
						GEO_CLOSE_NODE(),
					GEO_CLOSE_NODE(),
				GEO_CLOSE_NODE(),
				GEO_ANIMATED_PART(LAYER_OPAQUE, -3, -8, -42, NULL),
				GEO_OPEN_NODE(),
					GEO_ANIMATED_PART(LAYER_TRANSPARENT, 0, 0, 0, omega_Right_Thigh_Color_mesh_layer_1),
					GEO_OPEN_NODE(),
						GEO_DISPLAY_LIST(LAYER_TRANSPARENT, omega_Right_Thigh_Color_mesh_layer_4),
						GEO_ANIMATED_PART(LAYER_TRANSPARENT, 148, 0, 0, omega_Right_Leg_mesh_layer_4),
						GEO_OPEN_NODE(),
							GEO_ANIMATED_PART(LAYER_OPAQUE, 154, 0, 0, NULL),
							GEO_OPEN_NODE(),
								GEO_ASM(2, geo_mario_hand_foot_scaler),
								GEO_SCALE(LAYER_FORCE, 65536),
								GEO_OPEN_NODE(),
									GEO_DISPLAY_LIST(LAYER_TRANSPARENT, omega_Right_Shoe_DL_mesh_layer_1),
									GEO_DISPLAY_LIST(LAYER_TRANSPARENT, omega_Right_Shoe_DL_mesh_layer_5),
								GEO_CLOSE_NODE(),
							GEO_CLOSE_NODE(),
						GEO_CLOSE_NODE(),
					GEO_CLOSE_NODE(),
				GEO_CLOSE_NODE(),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout omega_2_LoD_Switch_opt0_Cap_State_Switch_opt2[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 163, 0, NULL),
		GEO_OPEN_NODE(),
			GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, omega_Butt_mesh_layer_1_mat_override_Metal_001_0),
			GEO_OPEN_NODE(),
				GEO_ASM(0, geo_move_mario_part_from_parent),
				GEO_ASM(0, geo_mario_tilt_torso),
				GEO_ROTATION_NODE(LAYER_FORCE, 0, 0, 0),
				GEO_OPEN_NODE(),
					GEO_ANIMATED_PART(LAYER_OPAQUE, 67, 0, 0, omega_Torso_mesh_layer_1_mat_override_Metal_001_0),
					GEO_OPEN_NODE(),
						GEO_ANIMATED_PART(LAYER_OPAQUE, 138, 0, 0, NULL),
						GEO_OPEN_NODE(),
							GEO_ASM(0, geo_mario_head_rotation),
							GEO_ROTATION_NODE(LAYER_FORCE, 0, 0, 0),
							GEO_OPEN_NODE(),
								GEO_SWITCH_CASE(0, geo_switch_mario_cap_on_off),
								GEO_OPEN_NODE(),
									GEO_NODE_START(),
									GEO_OPEN_NODE(),
										GEO_SWITCH_CASE(0, geo_switch_mario_eyes),
										GEO_OPEN_NODE(),
											GEO_NODE_START(),
											GEO_OPEN_NODE(),
												GEO_DISPLAY_LIST(LAYER_OPAQUE, omega_Head_DL_mesh_layer_1_mat_override_Metal_001_0),
												GEO_DISPLAY_LIST(LAYER_ALPHA, omega_Head_DL_mesh_layer_4_mat_override_Metal_001_0),
												GEO_DISPLAY_LIST(LAYER_TRANSPARENT, omega_Head_DL_mesh_layer_5_mat_override_Metal_001_0),
											GEO_CLOSE_NODE(),
										GEO_CLOSE_NODE(),
									GEO_CLOSE_NODE(),
								GEO_CLOSE_NODE(),
								GEO_TRANSLATE_ROTATE(LAYER_FORCE, 115, -51, 126, -15, 33, -133),
								GEO_OPEN_NODE(),
									GEO_ASM(1, geo_mario_rotate_wing_cap_wings),
									GEO_ROTATION_NODE(LAYER_FORCE, 0, 0, 0),
									GEO_OPEN_NODE(),
									GEO_CLOSE_NODE(),
								GEO_CLOSE_NODE(),
								GEO_TRANSLATE_ROTATE(LAYER_FORCE, 115, -51, -126, 15, -33, -133),
								GEO_OPEN_NODE(),
									GEO_ASM(0, geo_mario_rotate_wing_cap_wings),
									GEO_ROTATION_NODE(LAYER_FORCE, 0, 0, 0),
									GEO_OPEN_NODE(),
									GEO_CLOSE_NODE(),
								GEO_CLOSE_NODE(),
							GEO_CLOSE_NODE(),
						GEO_CLOSE_NODE(),
						GEO_ANIMATED_PART(LAYER_OPAQUE, 91, -10, 79, NULL),
						GEO_OPEN_NODE(),
							GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, omega_Left_Arm_Color_mesh_layer_1_mat_override_Metal_001_0),
							GEO_OPEN_NODE(),
								GEO_ANIMATED_PART(LAYER_OPAQUE, 129, 20, 0, omega_Left_Forearm_mesh_layer_1_mat_override_Metal_001_0),
								GEO_OPEN_NODE(),
									GEO_SWITCH_CASE(1, geo_switch_mario_hand),
									GEO_OPEN_NODE(),
										GEO_NODE_START(),
										GEO_OPEN_NODE(),
											GEO_ANIMATED_PART(LAYER_OPAQUE, 139, 0, 0, NULL),
											GEO_OPEN_NODE(),
												GEO_ASM(1, geo_mario_hand_foot_scaler),
												GEO_SCALE(LAYER_FORCE, 65536),
												GEO_OPEN_NODE(),
													GEO_DISPLAY_LIST(LAYER_OPAQUE, omega_Left_Hand_DL_mesh_layer_1_mat_override_Metal_001_0),
												GEO_CLOSE_NODE(),
											GEO_CLOSE_NODE(),
										GEO_CLOSE_NODE(),
									GEO_CLOSE_NODE(),
								GEO_CLOSE_NODE(),
							GEO_CLOSE_NODE(),
						GEO_CLOSE_NODE(),
						GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 92, -10, -79, 2, 0, 0),
						GEO_OPEN_NODE(),
							GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, NULL),
							GEO_OPEN_NODE(),
								GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, omega_Right_Arm_Color_mesh_layer_1_mat_override_Metal_001_0),
								GEO_OPEN_NODE(),
									GEO_ANIMATED_PART(LAYER_OPAQUE, 129, 21, 0, omega_Right_Forearm_mesh_layer_1_mat_override_Metal_001_0),
									GEO_OPEN_NODE(),
										GEO_SWITCH_CASE(0, geo_switch_mario_hand),
										GEO_OPEN_NODE(),
											GEO_NODE_START(),
											GEO_OPEN_NODE(),
												GEO_ANIMATED_PART(LAYER_OPAQUE, 139, 1, 0, NULL),
												GEO_OPEN_NODE(),
													GEO_ASM(0, geo_mario_hand_foot_scaler),
													GEO_SCALE(LAYER_FORCE, 65536),
													GEO_OPEN_NODE(),
														GEO_DISPLAY_LIST(LAYER_OPAQUE, omega_Right_Hand_DL_mesh_layer_1_mat_override_Metal_001_0),
													GEO_CLOSE_NODE(),
													GEO_HELD_OBJECT(0, 0, 0, 0, geo_switch_mario_hand_grab_pos),
												GEO_CLOSE_NODE(),
											GEO_CLOSE_NODE(),
										GEO_CLOSE_NODE(),
									GEO_CLOSE_NODE(),
								GEO_CLOSE_NODE(),
							GEO_CLOSE_NODE(),
						GEO_CLOSE_NODE(),
					GEO_CLOSE_NODE(),
				GEO_CLOSE_NODE(),
				GEO_ANIMATED_PART(LAYER_OPAQUE, -3, -8, 42, NULL),
				GEO_OPEN_NODE(),
					GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, omega_Left_Thigh_Color_mesh_layer_1_mat_override_Metal_001_0),
					GEO_OPEN_NODE(),
						GEO_DISPLAY_LIST(LAYER_ALPHA, omega_Left_Thigh_Color_mesh_layer_4_mat_override_Metal_001_0),
						GEO_ANIMATED_PART(LAYER_ALPHA, 148, 0, 0, omega_Left_Leg_mesh_layer_4_mat_override_Metal_001_0),
						GEO_OPEN_NODE(),
							GEO_ANIMATED_PART(LAYER_OPAQUE, 154, 0, 0, omega_Left_Shoe_mesh_layer_1_mat_override_Metal_001_0),
							GEO_OPEN_NODE(),
								GEO_DISPLAY_LIST(LAYER_TRANSPARENT, omega_Left_Shoe_mesh_layer_5_mat_override_Metal_001_0),
							GEO_CLOSE_NODE(),
						GEO_CLOSE_NODE(),
					GEO_CLOSE_NODE(),
				GEO_CLOSE_NODE(),
				GEO_ANIMATED_PART(LAYER_OPAQUE, -3, -8, -42, NULL),
				GEO_OPEN_NODE(),
					GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, omega_Right_Thigh_Color_mesh_layer_1_mat_override_Metal_001_0),
					GEO_OPEN_NODE(),
						GEO_DISPLAY_LIST(LAYER_ALPHA, omega_Right_Thigh_Color_mesh_layer_4_mat_override_Metal_001_0),
						GEO_ANIMATED_PART(LAYER_ALPHA, 148, 0, 0, omega_Right_Leg_mesh_layer_4_mat_override_Metal_001_0),
						GEO_OPEN_NODE(),
							GEO_ANIMATED_PART(LAYER_OPAQUE, 154, 0, 0, NULL),
							GEO_OPEN_NODE(),
								GEO_ASM(2, geo_mario_hand_foot_scaler),
								GEO_SCALE(LAYER_FORCE, 65536),
								GEO_OPEN_NODE(),
									GEO_DISPLAY_LIST(LAYER_OPAQUE, omega_Right_Shoe_DL_mesh_layer_1_mat_override_Metal_001_0),
									GEO_DISPLAY_LIST(LAYER_TRANSPARENT, omega_Right_Shoe_DL_mesh_layer_5_mat_override_Metal_001_0),
								GEO_CLOSE_NODE(),
							GEO_CLOSE_NODE(),
						GEO_CLOSE_NODE(),
					GEO_CLOSE_NODE(),
				GEO_CLOSE_NODE(),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout omega_2_LoD_Switch_opt0_Cap_State_Switch_opt3[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 163, 0, NULL),
		GEO_OPEN_NODE(),
			GEO_ANIMATED_PART(LAYER_TRANSPARENT, 0, 0, 0, omega_Butt_mesh_layer_1_mat_override_Metal_001_0),
			GEO_OPEN_NODE(),
				GEO_ASM(0, geo_move_mario_part_from_parent),
				GEO_ASM(0, geo_mario_tilt_torso),
				GEO_ROTATION_NODE(LAYER_FORCE, 0, 0, 0),
				GEO_OPEN_NODE(),
					GEO_ANIMATED_PART(LAYER_TRANSPARENT, 67, 0, 0, omega_Torso_mesh_layer_1_mat_override_Metal_001_0),
					GEO_OPEN_NODE(),
						GEO_ANIMATED_PART(LAYER_OPAQUE, 138, 0, 0, NULL),
						GEO_OPEN_NODE(),
							GEO_ASM(0, geo_mario_head_rotation),
							GEO_ROTATION_NODE(LAYER_FORCE, 0, 0, 0),
							GEO_OPEN_NODE(),
								GEO_SWITCH_CASE(0, geo_switch_mario_cap_on_off),
								GEO_OPEN_NODE(),
									GEO_NODE_START(),
									GEO_OPEN_NODE(),
										GEO_SWITCH_CASE(0, geo_switch_mario_eyes),
										GEO_OPEN_NODE(),
											GEO_NODE_START(),
											GEO_OPEN_NODE(),
												GEO_DISPLAY_LIST(LAYER_TRANSPARENT, omega_Head_DL_mesh_layer_1_mat_override_Metal_001_0),
												GEO_DISPLAY_LIST(LAYER_TRANSPARENT, omega_Head_DL_mesh_layer_4_mat_override_Metal_001_0),
												GEO_DISPLAY_LIST(LAYER_TRANSPARENT, omega_Head_DL_mesh_layer_5_mat_override_Metal_001_0),
											GEO_CLOSE_NODE(),
										GEO_CLOSE_NODE(),
									GEO_CLOSE_NODE(),
								GEO_CLOSE_NODE(),
								GEO_TRANSLATE_ROTATE(LAYER_FORCE, 115, -51, 126, -15, 33, -133),
								GEO_OPEN_NODE(),
									GEO_ASM(1, geo_mario_rotate_wing_cap_wings),
									GEO_ROTATION_NODE(LAYER_FORCE, 0, 0, 0),
									GEO_OPEN_NODE(),
									GEO_CLOSE_NODE(),
								GEO_CLOSE_NODE(),
								GEO_TRANSLATE_ROTATE(LAYER_FORCE, 115, -51, -126, 15, -33, -133),
								GEO_OPEN_NODE(),
									GEO_ASM(0, geo_mario_rotate_wing_cap_wings),
									GEO_ROTATION_NODE(LAYER_FORCE, 0, 0, 0),
									GEO_OPEN_NODE(),
									GEO_CLOSE_NODE(),
								GEO_CLOSE_NODE(),
							GEO_CLOSE_NODE(),
						GEO_CLOSE_NODE(),
						GEO_ANIMATED_PART(LAYER_OPAQUE, 91, -10, 79, NULL),
						GEO_OPEN_NODE(),
							GEO_ANIMATED_PART(LAYER_TRANSPARENT, 0, 0, 0, omega_Left_Arm_Color_mesh_layer_1_mat_override_Metal_001_0),
							GEO_OPEN_NODE(),
								GEO_ANIMATED_PART(LAYER_TRANSPARENT, 129, 20, 0, omega_Left_Forearm_mesh_layer_1_mat_override_Metal_001_0),
								GEO_OPEN_NODE(),
									GEO_SWITCH_CASE(1, geo_switch_mario_hand),
									GEO_OPEN_NODE(),
										GEO_NODE_START(),
										GEO_OPEN_NODE(),
											GEO_ANIMATED_PART(LAYER_OPAQUE, 139, 0, 0, NULL),
											GEO_OPEN_NODE(),
												GEO_ASM(1, geo_mario_hand_foot_scaler),
												GEO_SCALE(LAYER_FORCE, 65536),
												GEO_OPEN_NODE(),
													GEO_DISPLAY_LIST(LAYER_TRANSPARENT, omega_Left_Hand_DL_mesh_layer_1_mat_override_Metal_001_0),
												GEO_CLOSE_NODE(),
											GEO_CLOSE_NODE(),
										GEO_CLOSE_NODE(),
									GEO_CLOSE_NODE(),
								GEO_CLOSE_NODE(),
							GEO_CLOSE_NODE(),
						GEO_CLOSE_NODE(),
						GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 92, -10, -79, 2, 0, 0),
						GEO_OPEN_NODE(),
							GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, NULL),
							GEO_OPEN_NODE(),
								GEO_ANIMATED_PART(LAYER_TRANSPARENT, 0, 0, 0, omega_Right_Arm_Color_mesh_layer_1_mat_override_Metal_001_0),
								GEO_OPEN_NODE(),
									GEO_ANIMATED_PART(LAYER_TRANSPARENT, 129, 21, 0, omega_Right_Forearm_mesh_layer_1_mat_override_Metal_001_0),
									GEO_OPEN_NODE(),
										GEO_SWITCH_CASE(0, geo_switch_mario_hand),
										GEO_OPEN_NODE(),
											GEO_NODE_START(),
											GEO_OPEN_NODE(),
												GEO_ANIMATED_PART(LAYER_OPAQUE, 139, 1, 0, NULL),
												GEO_OPEN_NODE(),
													GEO_ASM(0, geo_mario_hand_foot_scaler),
													GEO_SCALE(LAYER_FORCE, 65536),
													GEO_OPEN_NODE(),
														GEO_DISPLAY_LIST(LAYER_TRANSPARENT, omega_Right_Hand_DL_mesh_layer_1_mat_override_Metal_001_0),
													GEO_CLOSE_NODE(),
													GEO_HELD_OBJECT(0, 0, 0, 0, geo_switch_mario_hand_grab_pos),
												GEO_CLOSE_NODE(),
											GEO_CLOSE_NODE(),
										GEO_CLOSE_NODE(),
									GEO_CLOSE_NODE(),
								GEO_CLOSE_NODE(),
							GEO_CLOSE_NODE(),
						GEO_CLOSE_NODE(),
					GEO_CLOSE_NODE(),
				GEO_CLOSE_NODE(),
				GEO_ANIMATED_PART(LAYER_OPAQUE, -3, -8, 42, NULL),
				GEO_OPEN_NODE(),
					GEO_ANIMATED_PART(LAYER_TRANSPARENT, 0, 0, 0, omega_Left_Thigh_Color_mesh_layer_1_mat_override_Metal_001_0),
					GEO_OPEN_NODE(),
						GEO_DISPLAY_LIST(LAYER_TRANSPARENT, omega_Left_Thigh_Color_mesh_layer_4_mat_override_Metal_001_0),
						GEO_ANIMATED_PART(LAYER_TRANSPARENT, 148, 0, 0, omega_Left_Leg_mesh_layer_4_mat_override_Metal_001_0),
						GEO_OPEN_NODE(),
							GEO_ANIMATED_PART(LAYER_TRANSPARENT, 154, 0, 0, omega_Left_Shoe_mesh_layer_1_mat_override_Metal_001_0),
							GEO_OPEN_NODE(),
								GEO_DISPLAY_LIST(LAYER_TRANSPARENT, omega_Left_Shoe_mesh_layer_5_mat_override_Metal_001_0),
							GEO_CLOSE_NODE(),
						GEO_CLOSE_NODE(),
					GEO_CLOSE_NODE(),
				GEO_CLOSE_NODE(),
				GEO_ANIMATED_PART(LAYER_OPAQUE, -3, -8, -42, NULL),
				GEO_OPEN_NODE(),
					GEO_ANIMATED_PART(LAYER_TRANSPARENT, 0, 0, 0, omega_Right_Thigh_Color_mesh_layer_1_mat_override_Metal_001_0),
					GEO_OPEN_NODE(),
						GEO_DISPLAY_LIST(LAYER_TRANSPARENT, omega_Right_Thigh_Color_mesh_layer_4_mat_override_Metal_001_0),
						GEO_ANIMATED_PART(LAYER_TRANSPARENT, 148, 0, 0, omega_Right_Leg_mesh_layer_4_mat_override_Metal_001_0),
						GEO_OPEN_NODE(),
							GEO_ANIMATED_PART(LAYER_OPAQUE, 154, 0, 0, NULL),
							GEO_OPEN_NODE(),
								GEO_ASM(2, geo_mario_hand_foot_scaler),
								GEO_SCALE(LAYER_FORCE, 65536),
								GEO_OPEN_NODE(),
									GEO_DISPLAY_LIST(LAYER_TRANSPARENT, omega_Right_Shoe_DL_mesh_layer_1_mat_override_Metal_001_0),
									GEO_DISPLAY_LIST(LAYER_TRANSPARENT, omega_Right_Shoe_DL_mesh_layer_5_mat_override_Metal_001_0),
								GEO_CLOSE_NODE(),
							GEO_CLOSE_NODE(),
						GEO_CLOSE_NODE(),
					GEO_CLOSE_NODE(),
				GEO_CLOSE_NODE(),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout omega_2_LoD_Switch_opt0_Cap_State_Switch_opt0_Capless_Switch_opt1[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_SWITCH_CASE(0, geo_switch_mario_eyes),
		GEO_OPEN_NODE(),
			GEO_NODE_START(),
			GEO_OPEN_NODE(),
				GEO_DISPLAY_LIST(LAYER_OPAQUE, omega_Head_DL_mesh_layer_1_mat_override_OmegaMouth_1),
				GEO_DISPLAY_LIST(LAYER_ALPHA, omega_Head_DL_mesh_layer_4_mat_override_OmegaMouth_1),
				GEO_DISPLAY_LIST(LAYER_TRANSPARENT, omega_Head_DL_mesh_layer_5_mat_override_OmegaMouth_1),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout omega_2_LoD_Switch_opt0_Cap_State_Switch_opt0_Capless_Switch_opt0_Eye_State_Switch_opt1[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, omega_Head_DL_mesh_layer_1_mat_override_OmegaMouth_1),
		GEO_DISPLAY_LIST(LAYER_ALPHA, omega_Head_DL_mesh_layer_4_mat_override_OmegaMouth_1),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, omega_Head_DL_mesh_layer_5_mat_override_OmegaMouth_1),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout omega_2_LoD_Switch_opt0_Cap_State_Switch_opt0_Capless_Switch_opt0_Eye_State_Switch_opt2[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, omega_Head_DL_mesh_layer_1_mat_override_OmegaMouth_1),
		GEO_DISPLAY_LIST(LAYER_ALPHA, omega_Head_DL_mesh_layer_4_mat_override_OmegaMouth_1),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, omega_Head_DL_mesh_layer_5_mat_override_OmegaMouth_1),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout omega_2_LoD_Switch_opt0_Cap_State_Switch_opt0_Capless_Switch_opt0_Eye_State_Switch_opt3[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, omega_Head_DL_mesh_layer_1_mat_override_OmegaMouth_1),
		GEO_DISPLAY_LIST(LAYER_ALPHA, omega_Head_DL_mesh_layer_4_mat_override_OmegaMouth_1),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, omega_Head_DL_mesh_layer_5_mat_override_OmegaMouth_1),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout omega_2_LoD_Switch_opt0_Cap_State_Switch_opt0_Capless_Switch_opt0_Eye_State_Switch_opt4[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, omega_Head_DL_mesh_layer_1_mat_override_OmegaMouth_1),
		GEO_DISPLAY_LIST(LAYER_ALPHA, omega_Head_DL_mesh_layer_4_mat_override_OmegaMouth_1),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, omega_Head_DL_mesh_layer_5_mat_override_OmegaMouth_1),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout omega_2_LoD_Switch_opt0_Cap_State_Switch_opt0_Capless_Switch_opt0_Eye_State_Switch_opt5[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, omega_Head_DL_mesh_layer_1_mat_override_OmegaMouth_1),
		GEO_DISPLAY_LIST(LAYER_ALPHA, omega_Head_DL_mesh_layer_4_mat_override_OmegaMouth_1),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, omega_Head_DL_mesh_layer_5_mat_override_OmegaMouth_1),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout omega_2_LoD_Switch_opt0_Cap_State_Switch_opt0_Capless_Switch_opt0_Eye_State_Switch_opt6[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, omega_Head_DL_mesh_layer_1_mat_override_OmegaMouth_1),
		GEO_DISPLAY_LIST(LAYER_ALPHA, omega_Head_DL_mesh_layer_4_mat_override_OmegaMouth_1),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, omega_Head_DL_mesh_layer_5_mat_override_OmegaMouth_1),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout omega_2_LoD_Switch_opt0_Cap_State_Switch_opt0_Capless_Switch_opt0_Eye_State_Switch_opt7[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, omega_Head_DL_mesh_layer_1_mat_override_OmegaMouth_1),
		GEO_DISPLAY_LIST(LAYER_ALPHA, omega_Head_DL_mesh_layer_4_mat_override_OmegaMouth_1),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, omega_Head_DL_mesh_layer_5_mat_override_OmegaMouth_1),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout omega_2_LoD_Switch_opt0_Cap_State_Switch_opt0_Left_Hand_Switch_opt1[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(LAYER_OPAQUE, 139, 0, 0, NULL),
		GEO_OPEN_NODE(),
			GEO_ASM(1, geo_mario_hand_foot_scaler),
			GEO_SCALE(LAYER_FORCE, 65536),
			GEO_OPEN_NODE(),
				GEO_DISPLAY_LIST(LAYER_OPAQUE, omega_Left_Hand_DL_mesh_layer_1_mat_override_OmegaMouth_1),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout omega_2_LoD_Switch_opt0_Cap_State_Switch_opt0_Right_Hand_Switch_opt1[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(LAYER_OPAQUE, 139, 1, 0, NULL),
		GEO_OPEN_NODE(),
			GEO_ASM(0, geo_mario_hand_foot_scaler),
			GEO_SCALE(LAYER_FORCE, 65536),
			GEO_OPEN_NODE(),
				GEO_DISPLAY_LIST(LAYER_OPAQUE, omega_Right_Hand_DL_mesh_layer_1_mat_override_OmegaMouth_1),
			GEO_CLOSE_NODE(),
			GEO_HELD_OBJECT(0, 0, 0, 0, geo_switch_mario_hand_grab_pos),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout omega_2_LoD_Switch_opt0_Cap_State_Switch_opt0_Right_Hand_Switch_opt2[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(LAYER_OPAQUE, 139, 1, 0, NULL),
		GEO_OPEN_NODE(),
			GEO_ASM(0, geo_mario_hand_foot_scaler),
			GEO_SCALE(LAYER_FORCE, 65536),
			GEO_OPEN_NODE(),
				GEO_DISPLAY_LIST(LAYER_OPAQUE, omega_Right_Hand_DL_mesh_layer_1_mat_override_OmegaMouth_1),
			GEO_CLOSE_NODE(),
			GEO_HELD_OBJECT(0, 0, 0, 0, geo_switch_mario_hand_grab_pos),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout omega_2_LoD_Switch_opt0_Cap_State_Switch_opt0_Right_Hand_Switch_opt3[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(LAYER_OPAQUE, 139, 1, 0, NULL),
		GEO_OPEN_NODE(),
			GEO_ASM(0, geo_mario_hand_foot_scaler),
			GEO_SCALE(LAYER_FORCE, 65536),
			GEO_OPEN_NODE(),
				GEO_DISPLAY_LIST(LAYER_OPAQUE, omega_Right_Hand_DL_mesh_layer_1_mat_override_OmegaMouth_1),
			GEO_CLOSE_NODE(),
			GEO_HELD_OBJECT(0, 0, 0, 0, geo_switch_mario_hand_grab_pos),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout omega_2_LoD_Switch_opt0_Cap_State_Switch_opt0_Right_Hand_Switch_opt4[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(LAYER_OPAQUE, 139, 1, 0, NULL),
		GEO_OPEN_NODE(),
			GEO_ASM(0, geo_mario_hand_foot_scaler),
			GEO_SCALE(LAYER_FORCE, 65536),
			GEO_OPEN_NODE(),
				GEO_DISPLAY_LIST(LAYER_OPAQUE, omega_Right_Hand_DL_mesh_layer_1_mat_override_OmegaMouth_1),
			GEO_CLOSE_NODE(),
			GEO_HELD_OBJECT(0, 0, 0, 0, geo_switch_mario_hand_grab_pos),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout omega_geo[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_SHADOW(1, 180, 100),
		GEO_OPEN_NODE(),
			GEO_SCALE(LAYER_FORCE, 16384),
			GEO_OPEN_NODE(),
				GEO_ASM(0, geo_mirror_mario_backface_culling),
				GEO_ASM(LAYER_OPAQUE + 3, geo_mario_set_player_colors),
GEO_ASM(LAYER_ALPHA + 3, geo_mario_set_player_colors),
GEO_ASM(LAYER_TRANSPARENT + 3, geo_mario_set_player_colors),

				GEO_ASM(0, geo_mirror_mario_set_alpha),
				GEO_SWITCH_CASE(0, geo_switch_mario_stand_run),
				GEO_OPEN_NODE(),
					GEO_NODE_START(),
					GEO_OPEN_NODE(),
						GEO_SWITCH_CASE(0, geo_switch_mario_cap_effect),
						GEO_OPEN_NODE(),
							GEO_NODE_START(),
							GEO_OPEN_NODE(),
								GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 163, 0, NULL),
								GEO_OPEN_NODE(),
									GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, omega_Butt_mesh_layer_1),
									GEO_OPEN_NODE(),
										GEO_ASM(0, geo_move_mario_part_from_parent),
										GEO_ASM(0, geo_mario_tilt_torso),
										GEO_ROTATION_NODE(LAYER_FORCE, 0, 0, 0),
										GEO_OPEN_NODE(),
											GEO_ANIMATED_PART(LAYER_OPAQUE, 67, 0, 0, omega_Torso_mesh_layer_1),
											GEO_OPEN_NODE(),
												GEO_ANIMATED_PART(LAYER_OPAQUE, 138, 0, 0, NULL),
												GEO_OPEN_NODE(),
													GEO_ASM(0, geo_mario_head_rotation),
													GEO_ROTATION_NODE(LAYER_FORCE, 0, 0, 0),
													GEO_OPEN_NODE(),
														GEO_SWITCH_CASE(0, geo_switch_mario_cap_on_off),
														GEO_OPEN_NODE(),
															GEO_NODE_START(),
															GEO_OPEN_NODE(),
																GEO_SWITCH_CASE(0, geo_switch_mario_eyes),
																GEO_OPEN_NODE(),
																	GEO_NODE_START(),
																	GEO_OPEN_NODE(),
																		GEO_DISPLAY_LIST(LAYER_OPAQUE, omega_Head_DL_mesh_layer_1),
																		GEO_DISPLAY_LIST(LAYER_ALPHA, omega_Head_DL_mesh_layer_4),
																		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, omega_Head_DL_mesh_layer_5),
																	GEO_CLOSE_NODE(),
																	GEO_BRANCH(1, omega_2_LoD_Switch_opt0_Cap_State_Switch_opt0_Capless_Switch_opt0_Eye_State_Switch_opt1),
																	GEO_BRANCH(1, omega_2_LoD_Switch_opt0_Cap_State_Switch_opt0_Capless_Switch_opt0_Eye_State_Switch_opt2),
																	GEO_BRANCH(1, omega_2_LoD_Switch_opt0_Cap_State_Switch_opt0_Capless_Switch_opt0_Eye_State_Switch_opt3),
																	GEO_BRANCH(1, omega_2_LoD_Switch_opt0_Cap_State_Switch_opt0_Capless_Switch_opt0_Eye_State_Switch_opt4),
																	GEO_BRANCH(1, omega_2_LoD_Switch_opt0_Cap_State_Switch_opt0_Capless_Switch_opt0_Eye_State_Switch_opt5),
																	GEO_BRANCH(1, omega_2_LoD_Switch_opt0_Cap_State_Switch_opt0_Capless_Switch_opt0_Eye_State_Switch_opt6),
																	GEO_BRANCH(1, omega_2_LoD_Switch_opt0_Cap_State_Switch_opt0_Capless_Switch_opt0_Eye_State_Switch_opt7),
																GEO_CLOSE_NODE(),
															GEO_CLOSE_NODE(),
															GEO_BRANCH(1, omega_2_LoD_Switch_opt0_Cap_State_Switch_opt0_Capless_Switch_opt1),
														GEO_CLOSE_NODE(),
														GEO_TRANSLATE_ROTATE(LAYER_FORCE, 115, -51, 126, -15, 33, -133),
														GEO_OPEN_NODE(),
															GEO_ASM(1, geo_mario_rotate_wing_cap_wings),
															GEO_ROTATION_NODE(LAYER_FORCE, 0, 0, 0),
															GEO_OPEN_NODE(),
															GEO_CLOSE_NODE(),
														GEO_CLOSE_NODE(),
														GEO_TRANSLATE_ROTATE(LAYER_FORCE, 115, -51, -126, 15, -33, -133),
														GEO_OPEN_NODE(),
															GEO_ASM(0, geo_mario_rotate_wing_cap_wings),
															GEO_ROTATION_NODE(LAYER_FORCE, 0, 0, 0),
															GEO_OPEN_NODE(),
															GEO_CLOSE_NODE(),
														GEO_CLOSE_NODE(),
													GEO_CLOSE_NODE(),
												GEO_CLOSE_NODE(),
												GEO_ANIMATED_PART(LAYER_OPAQUE, 91, -10, 79, NULL),
												GEO_OPEN_NODE(),
													GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, omega_Left_Arm_Color_mesh_layer_1),
													GEO_OPEN_NODE(),
														GEO_ANIMATED_PART(LAYER_OPAQUE, 129, 20, 0, omega_Left_Forearm_mesh_layer_1),
														GEO_OPEN_NODE(),
															GEO_SWITCH_CASE(1, geo_switch_mario_hand),
															GEO_OPEN_NODE(),
																GEO_NODE_START(),
																GEO_OPEN_NODE(),
																	GEO_ANIMATED_PART(LAYER_OPAQUE, 139, 0, 0, NULL),
																	GEO_OPEN_NODE(),
																		GEO_ASM(1, geo_mario_hand_foot_scaler),
																		GEO_SCALE(LAYER_FORCE, 65536),
																		GEO_OPEN_NODE(),
																			GEO_DISPLAY_LIST(LAYER_OPAQUE, omega_Left_Hand_DL_mesh_layer_1),
																		GEO_CLOSE_NODE(),
																	GEO_CLOSE_NODE(),
																GEO_CLOSE_NODE(),
																GEO_BRANCH(1, omega_2_LoD_Switch_opt0_Cap_State_Switch_opt0_Left_Hand_Switch_opt1),
															GEO_CLOSE_NODE(),
														GEO_CLOSE_NODE(),
													GEO_CLOSE_NODE(),
												GEO_CLOSE_NODE(),
												GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 92, -10, -79, 2, 0, 0),
												GEO_OPEN_NODE(),
													GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, NULL),
													GEO_OPEN_NODE(),
														GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, omega_Right_Arm_Color_mesh_layer_1),
														GEO_OPEN_NODE(),
															GEO_ANIMATED_PART(LAYER_OPAQUE, 129, 21, 0, omega_Right_Forearm_mesh_layer_1),
															GEO_OPEN_NODE(),
																GEO_SWITCH_CASE(0, geo_switch_mario_hand),
																GEO_OPEN_NODE(),
																	GEO_NODE_START(),
																	GEO_OPEN_NODE(),
																		GEO_ANIMATED_PART(LAYER_OPAQUE, 139, 1, 0, NULL),
																		GEO_OPEN_NODE(),
																			GEO_ASM(0, geo_mario_hand_foot_scaler),
																			GEO_SCALE(LAYER_FORCE, 65536),
																			GEO_OPEN_NODE(),
																				GEO_DISPLAY_LIST(LAYER_OPAQUE, omega_Right_Hand_DL_mesh_layer_1),
																			GEO_CLOSE_NODE(),
																			GEO_HELD_OBJECT(0, 0, 0, 0, geo_switch_mario_hand_grab_pos),
																		GEO_CLOSE_NODE(),
																	GEO_CLOSE_NODE(),
																	GEO_BRANCH(1, omega_2_LoD_Switch_opt0_Cap_State_Switch_opt0_Right_Hand_Switch_opt1),
																	GEO_BRANCH(1, omega_2_LoD_Switch_opt0_Cap_State_Switch_opt0_Right_Hand_Switch_opt2),
																	GEO_BRANCH(1, omega_2_LoD_Switch_opt0_Cap_State_Switch_opt0_Right_Hand_Switch_opt3),
																	GEO_BRANCH(1, omega_2_LoD_Switch_opt0_Cap_State_Switch_opt0_Right_Hand_Switch_opt4),
																GEO_CLOSE_NODE(),
															GEO_CLOSE_NODE(),
														GEO_CLOSE_NODE(),
													GEO_CLOSE_NODE(),
												GEO_CLOSE_NODE(),
											GEO_CLOSE_NODE(),
										GEO_CLOSE_NODE(),
										GEO_ANIMATED_PART(LAYER_OPAQUE, -3, -8, 42, NULL),
										GEO_OPEN_NODE(),
											GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, omega_Left_Thigh_Color_mesh_layer_1),
											GEO_OPEN_NODE(),
												GEO_DISPLAY_LIST(LAYER_ALPHA, omega_Left_Thigh_Color_mesh_layer_4),
												GEO_ANIMATED_PART(LAYER_ALPHA, 148, 0, 0, omega_Left_Leg_mesh_layer_4),
												GEO_OPEN_NODE(),
													GEO_ANIMATED_PART(LAYER_OPAQUE, 154, 0, 0, omega_Left_Shoe_mesh_layer_1),
													GEO_OPEN_NODE(),
														GEO_DISPLAY_LIST(LAYER_TRANSPARENT, omega_Left_Shoe_mesh_layer_5),
													GEO_CLOSE_NODE(),
												GEO_CLOSE_NODE(),
											GEO_CLOSE_NODE(),
										GEO_CLOSE_NODE(),
										GEO_ANIMATED_PART(LAYER_OPAQUE, -3, -8, -42, NULL),
										GEO_OPEN_NODE(),
											GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, omega_Right_Thigh_Color_mesh_layer_1),
											GEO_OPEN_NODE(),
												GEO_DISPLAY_LIST(LAYER_ALPHA, omega_Right_Thigh_Color_mesh_layer_4),
												GEO_ANIMATED_PART(LAYER_ALPHA, 148, 0, 0, omega_Right_Leg_mesh_layer_4),
												GEO_OPEN_NODE(),
													GEO_ANIMATED_PART(LAYER_OPAQUE, 154, 0, 0, NULL),
													GEO_OPEN_NODE(),
														GEO_ASM(2, geo_mario_hand_foot_scaler),
														GEO_SCALE(LAYER_FORCE, 65536),
														GEO_OPEN_NODE(),
															GEO_DISPLAY_LIST(LAYER_OPAQUE, omega_Right_Shoe_DL_mesh_layer_1),
															GEO_DISPLAY_LIST(LAYER_TRANSPARENT, omega_Right_Shoe_DL_mesh_layer_5),
														GEO_CLOSE_NODE(),
													GEO_CLOSE_NODE(),
												GEO_CLOSE_NODE(),
											GEO_CLOSE_NODE(),
										GEO_CLOSE_NODE(),
									GEO_CLOSE_NODE(),
								GEO_CLOSE_NODE(),
							GEO_CLOSE_NODE(),
							GEO_BRANCH(1, omega_2_LoD_Switch_opt0_Cap_State_Switch_opt1),
							GEO_BRANCH(1, omega_2_LoD_Switch_opt0_Cap_State_Switch_opt2),
							GEO_BRANCH(1, omega_2_LoD_Switch_opt0_Cap_State_Switch_opt3),
						GEO_CLOSE_NODE(),
					GEO_CLOSE_NODE(),
				GEO_CLOSE_NODE(),
				GEO_ASM(1, geo_mirror_mario_backface_culling),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, omega_material_revert_render_settings),
		GEO_DISPLAY_LIST(LAYER_ALPHA, omega_material_revert_render_settings),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, omega_material_revert_render_settings),
	GEO_CLOSE_NODE(),
	GEO_END(),
};
