extern const GeoLayout omega_2_LoD_Switch_opt0_Cap_State_Switch_opt1_Capless_Switch_opt1[];
extern const GeoLayout omega_2_LoD_Switch_opt0_Cap_State_Switch_opt1_Capless_Switch_opt0_Eye_State_Switch_opt1[];
extern const GeoLayout omega_2_LoD_Switch_opt0_Cap_State_Switch_opt1_Capless_Switch_opt0_Eye_State_Switch_opt2[];
extern const GeoLayout omega_2_LoD_Switch_opt0_Cap_State_Switch_opt1_Capless_Switch_opt0_Eye_State_Switch_opt3[];
extern const GeoLayout omega_2_LoD_Switch_opt0_Cap_State_Switch_opt1_Capless_Switch_opt0_Eye_State_Switch_opt4[];
extern const GeoLayout omega_2_LoD_Switch_opt0_Cap_State_Switch_opt1_Capless_Switch_opt0_Eye_State_Switch_opt5[];
extern const GeoLayout omega_2_LoD_Switch_opt0_Cap_State_Switch_opt1_Capless_Switch_opt0_Eye_State_Switch_opt6[];
extern const GeoLayout omega_2_LoD_Switch_opt0_Cap_State_Switch_opt1_Capless_Switch_opt0_Eye_State_Switch_opt7[];
extern const GeoLayout omega_2_LoD_Switch_opt0_Cap_State_Switch_opt1_Left_Hand_Switch_opt1[];
extern const GeoLayout omega_2_LoD_Switch_opt0_Cap_State_Switch_opt1_Right_Hand_Switch_opt1[];
extern const GeoLayout omega_2_LoD_Switch_opt0_Cap_State_Switch_opt1_Right_Hand_Switch_opt2[];
extern const GeoLayout omega_2_LoD_Switch_opt0_Cap_State_Switch_opt1_Right_Hand_Switch_opt3[];
extern const GeoLayout omega_2_LoD_Switch_opt0_Cap_State_Switch_opt1_Right_Hand_Switch_opt4[];
extern const GeoLayout omega_2_LoD_Switch_opt0_Cap_State_Switch_opt1[];
extern const GeoLayout omega_2_LoD_Switch_opt0_Cap_State_Switch_opt2[];
extern const GeoLayout omega_2_LoD_Switch_opt0_Cap_State_Switch_opt3[];
extern const GeoLayout omega_2_LoD_Switch_opt0_Cap_State_Switch_opt0_Capless_Switch_opt1[];
extern const GeoLayout omega_2_LoD_Switch_opt0_Cap_State_Switch_opt0_Capless_Switch_opt0_Eye_State_Switch_opt1[];
extern const GeoLayout omega_2_LoD_Switch_opt0_Cap_State_Switch_opt0_Capless_Switch_opt0_Eye_State_Switch_opt2[];
extern const GeoLayout omega_2_LoD_Switch_opt0_Cap_State_Switch_opt0_Capless_Switch_opt0_Eye_State_Switch_opt3[];
extern const GeoLayout omega_2_LoD_Switch_opt0_Cap_State_Switch_opt0_Capless_Switch_opt0_Eye_State_Switch_opt4[];
extern const GeoLayout omega_2_LoD_Switch_opt0_Cap_State_Switch_opt0_Capless_Switch_opt0_Eye_State_Switch_opt5[];
extern const GeoLayout omega_2_LoD_Switch_opt0_Cap_State_Switch_opt0_Capless_Switch_opt0_Eye_State_Switch_opt6[];
extern const GeoLayout omega_2_LoD_Switch_opt0_Cap_State_Switch_opt0_Capless_Switch_opt0_Eye_State_Switch_opt7[];
extern const GeoLayout omega_2_LoD_Switch_opt0_Cap_State_Switch_opt0_Left_Hand_Switch_opt1[];
extern const GeoLayout omega_2_LoD_Switch_opt0_Cap_State_Switch_opt0_Right_Hand_Switch_opt1[];
extern const GeoLayout omega_2_LoD_Switch_opt0_Cap_State_Switch_opt0_Right_Hand_Switch_opt2[];
extern const GeoLayout omega_2_LoD_Switch_opt0_Cap_State_Switch_opt0_Right_Hand_Switch_opt3[];
extern const GeoLayout omega_2_LoD_Switch_opt0_Cap_State_Switch_opt0_Right_Hand_Switch_opt4[];
extern const GeoLayout omega_geo[];
extern Lights1 omega_OmegaShirt_lights;
extern Lights1 omega_Metal_001_lights;
extern Lights1 omega_OmegaSkin_lights;
extern Lights1 omega_OmegaDarkness_lights;
extern Lights1 omega_OmegaKnit_lights;
extern Lights1 omega_OmegaHair_lights;
extern Lights1 omega_OmegaBeret_lights;
extern Lights1 omega_OmegaMouth_lights;
extern Lights1 omega_OmegaKnit2_lights;
extern Lights1 omega_OmegaSocks_lights;
extern Lights1 omega_OmegaShoes_lights;
extern Lights1 omega_OmegaShoeBase_lights;
extern Lights1 omega_OmegaShoeLaces_lights;
extern u8 omega_Metal_Shade_rgba16_rgba16[];
extern u8 omega_Metal_Light_rgba16_rgba16[];
extern u8 omega_omegamouth_ci8[];
extern u8 omega_omegamouth_pal_rgba16[];
extern u8 omega_omegaknit_ia8[];
extern u8 omega_omegasuspender_ia8[];
extern u8 omega_omegalaces_ia8[];
extern Vtx omega_Butt_mesh_layer_1_vtx_0[47];
extern Gfx omega_Butt_mesh_layer_1_tri_0[];
extern Vtx omega_Torso_mesh_layer_1_vtx_0[57];
extern Gfx omega_Torso_mesh_layer_1_tri_0[];
extern Vtx omega_Torso_mesh_layer_1_vtx_1[8];
extern Gfx omega_Torso_mesh_layer_1_tri_1[];
extern Vtx omega_Head_DL_mesh_layer_1_vtx_0[19];
extern Gfx omega_Head_DL_mesh_layer_1_tri_0[];
extern Vtx omega_Head_DL_mesh_layer_1_vtx_1[19];
extern Gfx omega_Head_DL_mesh_layer_1_tri_1[];
extern Vtx omega_Head_DL_mesh_layer_1_vtx_2[16];
extern Gfx omega_Head_DL_mesh_layer_1_tri_2[];
extern Vtx omega_Head_DL_mesh_layer_1_vtx_3[55];
extern Gfx omega_Head_DL_mesh_layer_1_tri_3[];
extern Vtx omega_Head_DL_mesh_layer_1_vtx_4[36];
extern Gfx omega_Head_DL_mesh_layer_1_tri_4[];
extern Vtx omega_Head_DL_mesh_layer_4_vtx_0[6];
extern Gfx omega_Head_DL_mesh_layer_4_tri_0[];
extern Vtx omega_Head_DL_mesh_layer_5_vtx_0[28];
extern Gfx omega_Head_DL_mesh_layer_5_tri_0[];
extern Vtx omega_Left_Arm_Color_mesh_layer_1_vtx_0[12];
extern Gfx omega_Left_Arm_Color_mesh_layer_1_tri_0[];
extern Vtx omega_Left_Forearm_mesh_layer_1_vtx_0[12];
extern Gfx omega_Left_Forearm_mesh_layer_1_tri_0[];
extern Vtx omega_Left_Hand_DL_mesh_layer_1_vtx_0[20];
extern Gfx omega_Left_Hand_DL_mesh_layer_1_tri_0[];
extern Vtx omega_Right_Arm_Color_mesh_layer_1_vtx_0[12];
extern Gfx omega_Right_Arm_Color_mesh_layer_1_tri_0[];
extern Vtx omega_Right_Forearm_mesh_layer_1_vtx_0[12];
extern Gfx omega_Right_Forearm_mesh_layer_1_tri_0[];
extern Vtx omega_Right_Hand_DL_mesh_layer_1_vtx_0[20];
extern Gfx omega_Right_Hand_DL_mesh_layer_1_tri_0[];
extern Vtx omega_Left_Thigh_Color_mesh_layer_1_vtx_0[11];
extern Gfx omega_Left_Thigh_Color_mesh_layer_1_tri_0[];
extern Vtx omega_Left_Thigh_Color_mesh_layer_4_vtx_0[15];
extern Gfx omega_Left_Thigh_Color_mesh_layer_4_tri_0[];
extern Vtx omega_Left_Leg_mesh_layer_4_vtx_0[20];
extern Gfx omega_Left_Leg_mesh_layer_4_tri_0[];
extern Vtx omega_Left_Shoe_mesh_layer_1_vtx_0[18];
extern Gfx omega_Left_Shoe_mesh_layer_1_tri_0[];
extern Vtx omega_Left_Shoe_mesh_layer_1_vtx_1[15];
extern Gfx omega_Left_Shoe_mesh_layer_1_tri_1[];
extern Vtx omega_Left_Shoe_mesh_layer_5_vtx_0[6];
extern Gfx omega_Left_Shoe_mesh_layer_5_tri_0[];
extern Vtx omega_Right_Thigh_Color_mesh_layer_1_vtx_0[11];
extern Gfx omega_Right_Thigh_Color_mesh_layer_1_tri_0[];
extern Vtx omega_Right_Thigh_Color_mesh_layer_4_vtx_0[15];
extern Gfx omega_Right_Thigh_Color_mesh_layer_4_tri_0[];
extern Vtx omega_Right_Leg_mesh_layer_4_vtx_0[20];
extern Gfx omega_Right_Leg_mesh_layer_4_tri_0[];
extern Vtx omega_Right_Shoe_DL_mesh_layer_1_vtx_0[18];
extern Gfx omega_Right_Shoe_DL_mesh_layer_1_tri_0[];
extern Vtx omega_Right_Shoe_DL_mesh_layer_1_vtx_1[15];
extern Gfx omega_Right_Shoe_DL_mesh_layer_1_tri_1[];
extern Vtx omega_Right_Shoe_DL_mesh_layer_5_vtx_0[6];
extern Gfx omega_Right_Shoe_DL_mesh_layer_5_tri_0[];
extern Gfx mat_omega_OmegaShirt[];
extern Gfx mat_omega_Metal_001[];
extern Gfx mat_revert_omega_Metal_001[];
extern Gfx mat_omega_OmegaSkin[];
extern Gfx mat_omega_OmegaDarkness[];
extern Gfx mat_omega_OmegaKnit[];
extern Gfx mat_omega_OmegaHair[];
extern Gfx mat_omega_OmegaBeret[];
extern Gfx mat_omega_OmegaMouth[];
extern Gfx mat_revert_omega_OmegaMouth[];
extern Gfx mat_omega_OmegaKnit2[];
extern Gfx mat_revert_omega_OmegaKnit2[];
extern Gfx mat_omega_OmegaSocks[];
extern Gfx mat_revert_omega_OmegaSocks[];
extern Gfx mat_omega_OmegaShoes[];
extern Gfx mat_omega_OmegaShoeBase[];
extern Gfx mat_omega_OmegaShoeLaces[];
extern Gfx mat_revert_omega_OmegaShoeLaces[];
extern Gfx omega_Butt_mesh_layer_1[];
extern Gfx omega_Butt_mesh_layer_1_mat_override_Metal_001_0[];
extern Gfx omega_Torso_mesh_layer_1[];
extern Gfx omega_Torso_mesh_layer_1_mat_override_Metal_001_0[];
extern Gfx omega_Head_DL_mesh_layer_1[];
extern Gfx omega_Head_DL_mesh_layer_1_mat_override_Metal_001_0[];
extern Gfx omega_Head_DL_mesh_layer_1_mat_override_OmegaMouth_1[];
extern Gfx omega_Head_DL_mesh_layer_4[];
extern Gfx omega_Head_DL_mesh_layer_4_mat_override_Metal_001_0[];
extern Gfx omega_Head_DL_mesh_layer_4_mat_override_OmegaMouth_1[];
extern Gfx omega_Head_DL_mesh_layer_5[];
extern Gfx omega_Head_DL_mesh_layer_5_mat_override_Metal_001_0[];
extern Gfx omega_Head_DL_mesh_layer_5_mat_override_OmegaMouth_1[];
extern Gfx omega_Left_Arm_Color_mesh_layer_1[];
extern Gfx omega_Left_Arm_Color_mesh_layer_1_mat_override_Metal_001_0[];
extern Gfx omega_Left_Forearm_mesh_layer_1[];
extern Gfx omega_Left_Forearm_mesh_layer_1_mat_override_Metal_001_0[];
extern Gfx omega_Left_Hand_DL_mesh_layer_1[];
extern Gfx omega_Left_Hand_DL_mesh_layer_1_mat_override_Metal_001_0[];
extern Gfx omega_Left_Hand_DL_mesh_layer_1_mat_override_OmegaMouth_1[];
extern Gfx omega_Right_Arm_Color_mesh_layer_1[];
extern Gfx omega_Right_Arm_Color_mesh_layer_1_mat_override_Metal_001_0[];
extern Gfx omega_Right_Forearm_mesh_layer_1[];
extern Gfx omega_Right_Forearm_mesh_layer_1_mat_override_Metal_001_0[];
extern Gfx omega_Right_Hand_DL_mesh_layer_1[];
extern Gfx omega_Right_Hand_DL_mesh_layer_1_mat_override_Metal_001_0[];
extern Gfx omega_Right_Hand_DL_mesh_layer_1_mat_override_OmegaMouth_1[];
extern Gfx omega_Left_Thigh_Color_mesh_layer_1[];
extern Gfx omega_Left_Thigh_Color_mesh_layer_1_mat_override_Metal_001_0[];
extern Gfx omega_Left_Thigh_Color_mesh_layer_4[];
extern Gfx omega_Left_Thigh_Color_mesh_layer_4_mat_override_Metal_001_0[];
extern Gfx omega_Left_Leg_mesh_layer_4[];
extern Gfx omega_Left_Leg_mesh_layer_4_mat_override_Metal_001_0[];
extern Gfx omega_Left_Shoe_mesh_layer_1[];
extern Gfx omega_Left_Shoe_mesh_layer_1_mat_override_Metal_001_0[];
extern Gfx omega_Left_Shoe_mesh_layer_5[];
extern Gfx omega_Left_Shoe_mesh_layer_5_mat_override_Metal_001_0[];
extern Gfx omega_Right_Thigh_Color_mesh_layer_1[];
extern Gfx omega_Right_Thigh_Color_mesh_layer_1_mat_override_Metal_001_0[];
extern Gfx omega_Right_Thigh_Color_mesh_layer_4[];
extern Gfx omega_Right_Thigh_Color_mesh_layer_4_mat_override_Metal_001_0[];
extern Gfx omega_Right_Leg_mesh_layer_4[];
extern Gfx omega_Right_Leg_mesh_layer_4_mat_override_Metal_001_0[];
extern Gfx omega_Right_Shoe_DL_mesh_layer_1[];
extern Gfx omega_Right_Shoe_DL_mesh_layer_1_mat_override_Metal_001_0[];
extern Gfx omega_Right_Shoe_DL_mesh_layer_5[];
extern Gfx omega_Right_Shoe_DL_mesh_layer_5_mat_override_Metal_001_0[];
extern Gfx omega_material_revert_render_settings[];
